version: '1'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: broker
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - "./static/rabbitmq-data:/var/lib/rabbitmq" 
    environment:
      RABBITMQ_DEFAULT_USER: "user" 
      RABBITMQ_DEFAULT_PASS: "password"

  redis:
    image: redis
    ports:
      - 11677:11677
